deployment:
  argocdrocksNginy:
    image:
      repository: nginx
      tag: alpine
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
